/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description Profil dan sakelar notifikasi email.
         */
        patch: operations["update_me_auth_me_patch"];
        trace?: never;
    };
    "/identity/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enroll Identity
         * @description Enroll your own face from three captures at different angles.
         *
         *     Requires lapis 1 consent to the current face consent text. Photos are only
         *     processed in memory; only an encrypted mean embedding is stored.
         */
        post: operations["enroll_identity_identity_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Identity */
        post: operations["verify_identity_identity_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Identity Profile */
        get: operations["get_identity_profile_identity_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock Identity */
        post: operations["lock_identity_identity_lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/me/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Media
         * @description Withdraw consent for one media; its embedding is deleted immediately.
         */
        post: operations["revoke_media_identity_me_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete My Identities
         * @description Delete all identities you own, with their embeddings, permissions and consents.
         */
        delete: operations["delete_my_identities_identity_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Permissions */
        get: operations["get_permissions_permissions_get"];
        put?: never;
        /** Set Permission */
        post: operations["set_permission_permissions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/analyze-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Intent */
        post: operations["analyze_intent_ai_analyze_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Intent Alias */
        post: operations["analyze_intent_alias_analyze_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Risk
         * @description Content risk only: consent and permissions are never inputs.
         */
        post: operations["analyze_risk_risk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Risk Alias */
        post: operations["analyze_risk_alias_analyze_risk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consent/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Consent
         * @description Minta persetujuan untuk permintaan REVIEW milikmu. Jawabannya sama, entah ada
         *     orang terdaftar di media itu atau tidak.
         */
        post: operations["request_consent_consent_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consent/request/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consent Status For Request */
        get: operations["consent_status_for_request_consent_request__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consent/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consent Inbox
         * @description Kotak consent: permintaan atas identitas milikmu.
         */
        get: operations["consent_inbox_consent_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consent/{consent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Consent */
        get: operations["get_consent_consent__consent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consent/{consent_id}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Respond Consent
         * @description Setujui dengan cakupan dan masa berlaku, tolak, atau blokir pengirim. Permintaan
         *     yang tertahan langsung dinilai ulang.
         */
        post: operations["respond_consent_consent__consent_id__respond_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consent/{consent_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Consent
         * @description Cabut persetujuan yang sudah diberikan. Sejak saat itu dianggap tidak ada.
         */
        post: operations["revoke_consent_consent__consent_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description Stateless deterministic policy evaluation over pre-computed signals.
         */
        post: operations["decide_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Requests
         * @description Riwayat permintaan milik sendiri.
         */
        get: operations["list_requests_requests_get"];
        put?: never;
        /**
         * Create Request
         * @description Gateway ARMOR: periksa permintaan (gambar, video, audio, atau teks saja) sebelum
         *     konten dibuat. Hasilnya ALLOW, REVIEW (ditahan menunggu persetujuan atau peninjauan),
         *     atau DENY, dengan alasan dan saran prompt.
         */
        post: operations["create_request_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Request
         * @description Status terbaru satu permintaan milik sendiri (misalnya setelah persetujuan dijawab).
         */
        get: operations["get_request_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Logs
         * @description The caller's own decision log (most recent first).
         */
        get: operations["get_logs_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export My Data */
        get: operations["export_my_data_me_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/circle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Circle
         * @description Lingkaran tepercaya sebuah identitas milikmu.
         */
        get: operations["list_circle_circle_get"];
        put?: never;
        /**
         * Add To Circle
         * @description Tambah orang ke lingkaran tepercaya lewat email, dengan cakupan dan masa berlaku.
         */
        post: operations["add_to_circle_circle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/circle/{member_ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Circle */
        delete: operations["remove_from_circle_circle__member_ref__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Notifications Read */
        post: operations["mark_notifications_read_notifications_read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity
         * @description Upaya penggunaan identitasmu per minggu: diblokir, disetujui, menunggu. Pengirim
         *     hanya ditampilkan jika ia mengajukan permintaan persetujuan.
         */
        get: operations["activity_dashboard_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cases
         * @description Kasus milikmu; untuk peninjau, kasus yang ditugaskan; untuk admin, semua kasus.
         */
        get: operations["list_cases_cases_get"];
        put?: never;
        /**
         * Create Appeal
         * @description Ajukan banding atas keputusan DENY milikmu, dengan konteks tambahan.
         */
        post: operations["create_appeal_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Dispute
         * @description Laporkan bahwa wajahmu didaftarkan orang lain, dengan verifikasi ulang lewat kamera.
         */
        post: operations["create_dispute_cases_dispute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Review */
        post: operations["start_review_cases__case_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Freeze Identity
         * @description Bekukan identitas yang disengketakan selama peninjauan.
         */
        post: operations["freeze_identity_cases__case_id__freeze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Case
         * @description Selesaikan kasus. Banding: pertahankan, atau koreksi label intent/risiko lalu
         *     policy engine memutuskan ulang. Sengketa: pindahkan kepemilikan, hapus pendaftaran
         *     palsu, atau tolak.
         */
        post: operations["resolve_case_cases__case_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Case */
        post: operations["assign_case_cases__case_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Audit Chain
         * @description Periksa integritas rantai hash audit log.
         */
        get: operations["verify_audit_chain_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppealCreate */
        AppealCreate: {
            /**
             * Kind
             * @default APPEAL
             * @constant
             */
            kind: "APPEAL";
            /** Request Id */
            request_id: string;
            /**
             * Note
             * @description Konteks tambahan dari requester
             */
            note: string;
        };
        /**
         * BiometricMedia
         * @description The two biometric media an owner controls separately (Lock, permission).
         * @enum {string}
         */
        BiometricMedia: "FACE" | "VOICE";
        /** CaseAssign */
        CaseAssign: {
            /** Reviewer Email */
            reviewer_email: string;
        };
        /** CaseResolve */
        CaseResolve: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "UPHOLD" | "RELABEL" | "TRANSFER" | "DELETE_ENROLLMENT" | "REJECT";
            /** Note */
            note?: string | null;
            corrected_intent?: components["schemas"]["Intent"] | null;
            corrected_risk?: components["schemas"]["RiskLevel"] | null;
        };
        /**
         * CircleAdd
         * @example {
         *       "email": "sinta@example.com",
         *       "expires_at": "2026-12-31T23:59:59",
         *       "identity_id": "<identity_id milikmu>",
         *       "intents": [
         *         "PERSONAL_CREATION"
         *       ],
         *       "media": "FACE"
         *     }
         */
        CircleAdd: {
            /** Identity Id */
            identity_id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Intents */
            intents?: components["schemas"]["Intent"][] | null;
            media?: components["schemas"]["BiometricMedia"] | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * ConsentAgreement
         * @description Lapis 1: explicit agreement to a specific version of docs/consent-text/.
         */
        ConsentAgreement: {
            /** Agreed */
            agreed: boolean;
            /** Text Version */
            text_version: string;
        };
        /**
         * ConsentAnswer
         * @description APPROVE with a scope and validity, DENY, or BLOCK (deny and block the sender).
         * @example {
         *       "action": "APPROVE",
         *       "intent": "COMMERCIAL_USE",
         *       "media": "FACE",
         *       "validity": "DAYS_7"
         *     }
         * @example {
         *       "action": "BLOCK"
         *     }
         */
        ConsentAnswer: {
            /**
             * Action
             * @enum {string}
             */
            action: "APPROVE" | "DENY" | "BLOCK";
            intent?: components["schemas"]["Intent"] | null;
            media?: components["schemas"]["BiometricMedia"] | null;
            /**
             * Validity
             * @default ONCE
             * @enum {string}
             */
            validity: "ONCE" | "DAYS_1" | "DAYS_7" | "DAYS_30" | "UNTIL";
            /** Until */
            until?: string | null;
        };
        /** ConsentInboxResponse */
        ConsentInboxResponse: {
            /** Items */
            items: components["schemas"]["ConsentItem"][];
            /** Pending */
            pending: number;
        };
        /** ConsentItem */
        ConsentItem: {
            /** Consent Id */
            consent_id: string;
            /** Identity Id */
            identity_id: string;
            /** Requester Email */
            requester_email?: string | null;
            /** Intent */
            intent?: string | null;
            /** Media */
            media?: string | null;
            /** Prompt */
            prompt?: string | null;
            /** Media Type */
            media_type?: string | null;
            status: components["schemas"]["ConsentStatus"];
            /** State */
            state: string;
            /** Validity */
            validity?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Answered At */
            answered_at?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * ConsentRequest
         * @description Ask for consent on one of your own requests that is waiting for review.
         */
        ConsentRequest: {
            /** Request Id */
            request_id: string;
            intent?: components["schemas"]["Intent"] | null;
            media?: components["schemas"]["BiometricMedia"] | null;
        };
        /** ConsentRequestResponse */
        ConsentRequestResponse: {
            /** Request Id */
            request_id: string;
            status: components["schemas"]["ConsentStatus"];
            /**
             * Message
             * @default Permintaan persetujuan dikirim jika diperlukan.
             */
            message: string;
        };
        /** ConsentRequestStatusResponse */
        ConsentRequestStatusResponse: {
            /** Request Id */
            request_id: string;
            status: components["schemas"]["ConsentStatus"];
        };
        /**
         * ConsentStatus
         * @enum {string}
         */
        ConsentStatus: "GRANTED" | "DENIED" | "PENDING" | "NONE";
        /**
         * Decision
         * @enum {string}
         */
        Decision: "ALLOW" | "REVIEW" | "DENY";
        /** DecisionBlock */
        DecisionBlock: {
            action: components["schemas"]["Decision"];
            /** Reason Code */
            reason_code: string;
            /** Reason */
            reason: string;
            /** Suggestion */
            suggestion?: string | null;
            /**
             * Label Required
             * @default false
             */
            label_required: boolean;
        };
        /**
         * DecisionRequest
         * @description Stateless policy evaluation over pre-computed signals (for testing and demos).
         */
        DecisionRequest: {
            /** Targets */
            targets?: components["schemas"]["DecisionTarget"][];
            intent: components["schemas"]["Intent"];
            risk_level?: components["schemas"]["RiskLevel"] | null;
            /** @default IMAGE */
            media_type: components["schemas"]["MediaType"];
            /** Intent Confidence */
            intent_confidence?: number | null;
            /** Realism */
            realism?: number | null;
            /** Unavailable */
            unavailable?: string[];
            /** Prompt */
            prompt?: string | null;
        };
        /** DecisionResponse */
        DecisionResponse: {
            decision: components["schemas"]["Decision"];
            /** Reason Code */
            reason_code: string;
            /** Reason */
            reason: string;
            /** Suggestion */
            suggestion?: string | null;
            /** Requester Code */
            requester_code: string;
            /** Requester Message */
            requester_message: string;
            effective_intent: components["schemas"]["Intent"];
            /** Label Required */
            label_required: boolean;
            /** Per Target Detail */
            per_target_detail: components["schemas"]["TargetDetail"][];
        };
        /** DecisionTarget */
        DecisionTarget: {
            /** @default FACE */
            source: components["schemas"]["TargetSource"];
            target_type: components["schemas"]["IdentityTarget"];
            /** Identity Id */
            identity_id?: string | null;
            /** Score */
            score?: number | null;
            /** @default NONE */
            lock_level: components["schemas"]["LockLevel"];
            /** @default NONE */
            consent: components["schemas"]["ConsentStatus"];
            permission?: components["schemas"]["PermissionDecision"] | null;
            /**
             * In Trusted Circle
             * @default false
             */
            in_trusted_circle: boolean;
            /**
             * Guardian Child
             * @default false
             */
            guardian_child: boolean;
        };
        /** DeleteIdentityResponse */
        DeleteIdentityResponse: {
            /** Deleted Identities */
            deleted_identities: number;
            /** Message */
            message: string;
        };
        /**
         * DisputeCreate
         * @description Re-verify your own face live (three captures, like enrollment).
         */
        DisputeCreate: {
            /** Images */
            images: string[];
            consent: components["schemas"]["ConsentAgreement"];
            /** Note */
            note?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdentityBlock
         * @description Requester-safe: SELF / OTHER / NONE summary plus one entry per person found.
         *     Never a target identity id, whether it is registered, or a match score.
         */
        IdentityBlock: {
            /** Target */
            target: string;
            /**
             * People
             * @default []
             */
            people: components["schemas"]["PersonBlock"][];
        };
        /** IdentityEnrollRequest */
        IdentityEnrollRequest: {
            /** Images */
            images: string[];
            consent: components["schemas"]["ConsentAgreement"];
            /** Display Name */
            display_name?: string | null;
        };
        /** IdentityEnrollResponse */
        IdentityEnrollResponse: {
            /** Identity Id */
            identity_id: string;
            /** Status */
            status: string;
            /** Face Enrolled */
            face_enrolled: boolean;
            /** Message */
            message: string;
        };
        /** IdentityLockRequest */
        IdentityLockRequest: {
            /** Identity Id */
            identity_id: string;
            /** @default ALL */
            level: components["schemas"]["LockLevel"];
            media?: components["schemas"]["BiometricMedia"] | null;
        };
        /** IdentityLockResponse */
        IdentityLockResponse: {
            /** Identity Id */
            identity_id: string;
            /** Status */
            status: string;
            face_lock: components["schemas"]["LockLevel"];
            voice_lock: components["schemas"]["LockLevel"];
            /** Message */
            message: string;
        };
        /** IdentityProfileResponse */
        IdentityProfileResponse: {
            /** Identity Id */
            identity_id: string;
            /** Status */
            status: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * Is Child
             * @default false
             */
            is_child: boolean;
            /** Face Enrolled */
            face_enrolled: boolean;
            /** Voice Enrolled */
            voice_enrolled: boolean;
            /** @default NONE */
            face_lock: components["schemas"]["LockLevel"];
            /** @default NONE */
            voice_lock: components["schemas"]["LockLevel"];
        };
        /**
         * IdentityTarget
         * @enum {string}
         */
        IdentityTarget: "SELF" | "OTHER_REGISTERED" | "OTHER_UNREGISTERED" | "UNCLEAR";
        /** IdentityVerifyRequest */
        IdentityVerifyRequest: {
            /** Image */
            image: string;
            /** Identity Id */
            identity_id?: string | null;
        };
        /** IdentityVerifyResponse */
        IdentityVerifyResponse: {
            /** Identity Id */
            identity_id: string;
            /** Match */
            match: boolean;
            /** Score */
            score?: number | null;
            /** Status */
            status: string;
            /**
             * Ai Available
             * @default true
             */
            ai_available: boolean;
        };
        /**
         * Intent
         * @enum {string}
         */
        Intent: "PERSONAL_CREATION" | "PERSONAL_EDITING" | "SATIRE_PARODY" | "COMMERCIAL_USE" | "POLITICAL_USE" | "IMPERSONATION" | "DEFAMATION" | "SEXUAL_EXPLICIT" | "DECEPTIVE" | "UNCERTAIN";
        /** IntentBlock */
        IntentBlock: {
            label: components["schemas"]["Intent"];
            /** Confidence */
            confidence: number;
            /** Ai Available */
            ai_available: boolean;
        };
        /** IntentRequest */
        IntentRequest: {
            /** Prompt */
            prompt: string;
        };
        /** IntentResponse */
        IntentResponse: {
            /** Intent */
            intent: string;
            /** Confidence */
            confidence: number;
            /**
             * Ai Available
             * @default true
             */
            ai_available: boolean;
            /** Model Version */
            model_version?: string | null;
        };
        /**
         * LockLevel
         * @enum {string}
         */
        LockLevel: "NONE" | "COMMERCIAL_POLITICAL" | "ALL";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MarkRead */
        MarkRead: {
            /**
             * Ids
             * @description None = tandai semua dibaca
             */
            ids?: string[] | null;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Role
             * @default USER
             */
            role: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * Email Notifications
             * @default false
             */
            email_notifications: boolean;
        };
        /** MeUpdate */
        MeUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Email Notifications */
            email_notifications?: boolean | null;
        };
        /**
         * MediaType
         * @enum {string}
         */
        MediaType: "IMAGE" | "VIDEO" | "AUDIO" | "TEXT_ONLY";
        /**
         * PermissionDecision
         * @enum {string}
         */
        PermissionDecision: "ALLOW" | "REVIEW" | "DENY";
        /** PermissionSetRequest */
        PermissionSetRequest: {
            /** Identity Id */
            identity_id: string;
            intent: components["schemas"]["Intent"];
            /** @default FACE */
            media: components["schemas"]["BiometricMedia"];
            decision: components["schemas"]["PermissionDecision"];
        };
        /** PermissionSetResponse */
        PermissionSetResponse: {
            /** Identity Id */
            identity_id: string;
            intent: components["schemas"]["Intent"];
            media: components["schemas"]["BiometricMedia"];
            decision: components["schemas"]["PermissionDecision"];
            /**
             * Message
             * @default Permission updated successfully
             */
            message: string;
        };
        /** PermissionsResponse */
        PermissionsResponse: {
            /** Identity Id */
            identity_id: string;
            /** Permissions */
            permissions: {
                [key: string]: {
                    [key: string]: components["schemas"]["PermissionDecision"];
                };
            };
            /** Locked Intents */
            locked_intents: components["schemas"]["Intent"][];
        };
        /** PersonBlock */
        PersonBlock: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Quality Ok */
            quality_ok: boolean;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RegisterResponse */
        RegisterResponse: {
            /** User Id */
            user_id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Message
             * @default User registered successfully
             */
            message: string;
        };
        /**
         * RequestCreate
         * @description Who is in the media is found by ARMOR, never named by the client.
         *     Send at most one of image, video, audio (base64); none = text only.
         * @example {
         *       "image": "<base64 PNG/JPEG>",
         *       "prompt": "Buat karikatur superhero dari foto ini."
         *     }
         */
        RequestCreate: {
            /** Prompt */
            prompt: string;
            /** Image */
            image?: string | null;
            /** Video */
            video?: string | null;
            /** Audio */
            audio?: string | null;
            media_type?: components["schemas"]["MediaType"] | null;
            /**
             * Allow Training
             * @default false
             */
            allow_training: boolean;
        };
        /**
         * RequestDecisionResponse
         * @example {
         *       "checks_unavailable": [],
         *       "decision": {
         *         "action": "DENY",
         *         "label_required": false,
         *         "reason": "Konten yang membuat orang lain terlihat seperti tahanan dapat mencemarkan nama baiknya.",
         *         "reason_code": "HARMFUL_DEFAMATION",
         *         "suggestion": "Buat karikatur superhero dari foto ini."
         *       },
         *       "identity": {
         *         "people": [
         *           {
         *             "quality_ok": true,
         *             "source": "FACE",
         *             "target": "OTHER"
         *           }
         *         ],
         *         "target": "OTHER"
         *       },
         *       "intent": {
         *         "ai_available": true,
         *         "confidence": 0.94,
         *         "label": "DEFAMATION"
         *       },
         *       "media_type": "IMAGE",
         *       "request_id": "7d1c2f7e-5d8b-4e3f-9a51-2b9c0f1e6a10",
         *       "risk": {
         *         "ai_available": false,
         *         "level": "CRITICAL",
         *         "score": 95
         *       },
         *       "status": "FINAL",
         *       "timing_ms": {
         *         "face": 41,
         *         "intent": 3,
         *         "policy": 2,
         *         "risk": 1,
         *         "router": 0
         *       }
         *     }
         */
        RequestDecisionResponse: {
            /** Request Id */
            request_id: string;
            /** Status */
            status: string;
            media_type: components["schemas"]["MediaType"];
            identity: components["schemas"]["IdentityBlock"];
            intent: components["schemas"]["IntentBlock"];
            risk: components["schemas"]["RiskBlock"];
            decision: components["schemas"]["DecisionBlock"];
            /**
             * Checks Unavailable
             * @default []
             */
            checks_unavailable: string[];
            /**
             * Timing Ms
             * @default {}
             */
            timing_ms: {
                [key: string]: number;
            };
        };
        /** RequestDetail */
        RequestDetail: {
            /** Request Id */
            request_id: string;
            /** Status */
            status: string;
            /** Prompt */
            prompt: string;
            /** Media Type */
            media_type?: string | null;
            decision: components["schemas"]["DecisionBlock"];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** RequestHistoryItem */
        RequestHistoryItem: {
            /** Request Id */
            request_id: string;
            /** Status */
            status?: string | null;
            /** Intent */
            intent: string | null;
            /** Risk Level */
            risk_level: string | null;
            /** Decision */
            decision: string;
            /** Reason Code */
            reason_code: string | null;
            /** Created At */
            created_at: string;
        };
        /** RequestHistoryResponse */
        RequestHistoryResponse: {
            /** Items */
            items: components["schemas"]["RequestHistoryItem"][];
            /** Total */
            total: number;
        };
        /** RevokeResponse */
        RevokeResponse: {
            /** Identity Id */
            identity_id: string;
            media: components["schemas"]["BiometricMedia"];
            /**
             * Revoked At
             * Format: date-time
             */
            revoked_at: string;
            /** Message */
            message: string;
        };
        /** RiskBlock */
        RiskBlock: {
            /** Score */
            score?: number | null;
            level?: components["schemas"]["RiskLevel"] | null;
            /** Ai Available */
            ai_available: boolean;
            /**
             * Top Features
             * @default []
             */
            top_features: {
                [key: string]: unknown;
            }[];
        };
        /** RiskFactor */
        RiskFactor: {
            /** Feature */
            feature: string;
            /** Value */
            value?: unknown;
            /** Effect */
            effect?: number | null;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /** RiskRequest */
        RiskRequest: {
            /**
             * Identity Target
             * @default NONE
             */
            identity_target: string;
            intent: components["schemas"]["Intent"];
            /**
             * Prompt
             * @default
             */
            prompt: string;
            /** @default IMAGE */
            media_type: components["schemas"]["MediaType"];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /** RiskResponse */
        RiskResponse: {
            /** Risk Level */
            risk_level: string;
            /** Risk Score */
            risk_score: number;
            /**
             * Ai Available
             * @default true
             */
            ai_available: boolean;
            /** Model Version */
            model_version?: string | null;
            /**
             * Top Features
             * @default []
             */
            top_features: components["schemas"]["RiskFactor"][];
            /**
             * Features
             * @default {}
             */
            features: {
                [key: string]: unknown;
            };
        };
        /** TargetDetail */
        TargetDetail: {
            source: components["schemas"]["TargetSource"];
            target_type: components["schemas"]["IdentityTarget"];
            /** Identity Id */
            identity_id?: string | null;
            /** Score */
            score?: number | null;
            decision: components["schemas"]["Decision"];
            /** Reason Code */
            reason_code: string;
            /** Reason */
            reason: string;
        };
        /**
         * TargetSource
         * @enum {string}
         */
        TargetSource: "FACE" | "VOICE" | "TEXT";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** User Id */
            user_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    update_me_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_identity_identity_enroll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityEnrollRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityEnrollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_identity_identity_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_identity_profile_identity_profile_get: {
        parameters: {
            query?: {
                identity_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_identity_identity_lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityLockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityLockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_media_identity_me_revoke_post: {
        parameters: {
            query: {
                media: components["schemas"]["BiometricMedia"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_my_identities_identity_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteIdentityResponse"];
                };
            };
        };
    };
    get_permissions_permissions_get: {
        parameters: {
            query: {
                identity_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_permission_permissions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermissionSetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionSetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_intent_ai_analyze_intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_intent_alias_analyze_intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_risk_risk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_risk_alias_analyze_risk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_consent_consent_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consent_status_for_request_consent_request__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentRequestStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consent_inbox_consent_inbox_get: {
        parameters: {
            query?: {
                status?: ("pending" | "answered") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentInboxResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_consent_consent__consent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    respond_consent_consent__consent_id__respond_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentAnswer"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_consent_consent__consent_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                consent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_requests_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_logs_logs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_my_data_me_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_circle_circle_get: {
        parameters: {
            query: {
                identity_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_circle_circle_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CircleAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_circle_circle__member_ref__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_notifications_get: {
        parameters: {
            query?: {
                unread?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_notifications_read_notifications_read_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkRead"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activity_dashboard_activity_get: {
        parameters: {
            query?: {
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_appeal_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppealCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dispute_cases_dispute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_review_cases__case_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    freeze_identity_cases__case_id__freeze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_case_cases__case_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseResolve"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_case_cases__case_id__assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseAssign"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_audit_chain_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
