// GENERATED by scripts/sync-content.mjs from docs/consent-text/. Do not edit.
export const CONSENT_TEXT = {
  "face": {
    "version": "face-v1",
    "title": "Persetujuan pemrosesan wajah",
    "intro": "Sebelum mendaftarkan wajahmu, baca poin berikut.",
    "sections": [
      {
        "heading": "Data apa yang diproses",
        "text": "Tiga foto wajahmu dari kamera, diambil dari sudut lurus, sedikit ke kiri, dan sedikit ke kanan. ARMOR mengubah foto itu menjadi pola wajah berupa deretan angka. Fotonya tidak disimpan. Yang disimpan hanya pola angka itu, dalam keadaan terenkripsi."
      },
      {
        "heading": "Untuk apa",
        "text": "Mengenali wajahmu saat seseorang mencoba memakainya di layanan AI yang terhubung dengan ARMOR, lalu menerapkan pengaturan yang kamu pilih: Lock, izin per tujuan, dan kotak persetujuan. ARMOR tidak pernah menebak nama siapa pun dari wajah, dan pola wajahmu tidak dikirim ke layanan pihak lain."
      },
      {
        "heading": "Berapa lama disimpan",
        "text": "Sampai kamu mencabut persetujuan ini atau menghapus identitasmu."
      },
      {
        "heading": "Cara mencabut",
        "text": "Buka Identitas, lalu Data saya, lalu pilih Cabut persetujuan wajah. Pola wajahmu langsung dihapus. Kamu juga bisa menghapus seluruh identitas di halaman yang sama."
      },
      {
        "heading": "Hakmu",
        "text": "Kamu berhak melihat dan mengunduh data yang ARMOR simpan tentangmu, dan berhak menarik persetujuan kapan saja sesuai UU No. 27 Tahun 2022 tentang Pelindungan Data Pribadi."
      }
    ],
    "closing": "Dengan mencentang kotak persetujuan, kamu menyatakan bahwa wajah yang didaftarkan adalah wajahmu sendiri dan kamu setuju wajahmu diproses seperti dijelaskan di atas."
  },
  "voice": {
    "version": "voice-v1",
    "title": "Persetujuan pemrosesan suara",
    "intro": "Sebelum mendaftarkan suaramu, baca poin berikut.",
    "sections": [
      {
        "heading": "Data apa yang diproses",
        "text": "Rekaman suaramu saat membaca tiga kalimat acak yang ditampilkan di layar. ARMOR mengubah rekaman itu menjadi pola suara berupa deretan angka, dan memeriksa bahwa kalimat yang kamu ucapkan sesuai serta bukan rekaman ulang atau suara buatan. Rekamannya tidak disimpan. Yang disimpan hanya pola angka itu, dalam keadaan terenkripsi."
      },
      {
        "heading": "Untuk apa",
        "text": "Mengenali suaramu saat seseorang mencoba meniru atau memakainya di layanan AI yang terhubung dengan ARMOR, lalu menerapkan pengaturan yang kamu pilih. ARMOR tidak pernah menebak nama siapa pun dari suara, dan pola suaramu tidak dikirim ke layanan pihak lain."
      },
      {
        "heading": "Berapa lama disimpan",
        "text": "Sampai kamu mencabut persetujuan ini atau menghapus identitasmu."
      },
      {
        "heading": "Cara mencabut",
        "text": "Buka Identitas, lalu Data saya, lalu pilih Cabut persetujuan suara. Pola suaramu langsung dihapus, tanpa mengubah pendaftaran wajahmu."
      },
      {
        "heading": "Hakmu",
        "text": "Kamu berhak melihat dan mengunduh data yang ARMOR simpan tentangmu, dan berhak menarik persetujuan kapan saja sesuai UU No. 27 Tahun 2022 tentang Pelindungan Data Pribadi."
      }
    ],
    "closing": "Dengan mencentang kotak persetujuan, kamu menyatakan bahwa suara yang didaftarkan adalah suaramu sendiri dan kamu setuju suaramu diproses seperti dijelaskan di atas."
  }
} as const;
