// Copies the versioned consent texts from docs/consent-text/ into the app, so the
// text a user agrees to is exactly the text whose version the backend records.
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "..", "docs", "consent-text");
const out = join(here, "..", "src", "content", "consent.ts");

const texts = {};
for (const file of readdirSync(src).filter((f) => /^(face|voice)-v\d+\.md$/.test(f))) {
  const raw = readFileSync(join(src, file), "utf8").replace(/\r\n/g, "\n");
  const version = /^version:\s*(\S+)/m.exec(raw)[1];
  const media = /^media:\s*(\S+)/m.exec(raw)[1];
  const body = raw.replace(/^---[\s\S]*?---\n/, "");
  const title = /^# (.+)$/m.exec(body)[1];
  const sections = [];
  let intro = "";
  let closing = "";
  for (const block of body.split(/\n\n+/).slice(1)) {
    const m = /^\*\*(.+?)\*\*\n([\s\S]+)$/.exec(block.trim());
    if (m) sections.push({ heading: m[1], text: m[2].trim() });
    else if (!sections.length) intro = block.trim();
    else closing = block.trim();
  }
  const key = media.toLowerCase();
  const n = Number(version.split("-v")[1]);
  if (!texts[key] || n > texts[key].n) texts[key] = { n, version, title, intro, sections, closing };
}

mkdirSync(dirname(out), { recursive: true });
const data = Object.fromEntries(Object.entries(texts).map(([k, { n: _n, ...v }]) => [k, v]));
writeFileSync(
  out,
  `// GENERATED by scripts/sync-consent.mjs from docs/consent-text/. Do not edit.\n` +
    `export const CONSENT_TEXT = ${JSON.stringify(data, null, 2)} as const;\n`,
);
console.log(`consent texts: ${Object.values(texts).map((t) => t.version).join(", ")}`);
