// Copies the versioned consent texts (docs/consent-text/) and the legal pages
// (docs/TERMS.md, docs/PRIVACY.md) into the app, so what users read in the app is
// exactly what the repository documents and the backend versions.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const docs = join(here, "..", "..", "docs");
const outDir = join(here, "..", "src", "content");
const read = (p) => readFileSync(p, "utf8").replace(/\r\n/g, "\n");

const texts = {};
const consentDir = join(docs, "consent-text");
for (const file of readdirSync(consentDir).filter((f) => /^(face|voice)-v\d+\.md$/.test(f))) {
  const raw = read(join(consentDir, file));
  const version = /^version:\s*(\S+)/m.exec(raw)[1];
  const media = /^media:\s*(\S+)/m.exec(raw)[1];
  const body = raw.replace(/^---[\s\S]*?---\n/, "");
  const title = /^# (.+)$/m.exec(body)[1];
  const sections = [];
  let intro = "";
  let closing = "";
  for (const block of body.split(/\n\n+/).slice(1)) {
    const m = /^\*\*(.+?)\*\*\n([\s\S]+)$/.exec(block.trim());
    if (m) sections.push({ heading: m[1], text: m[2].trim() });
    else if (!sections.length) intro = block.trim();
    else closing = block.trim();
  }
  const key = media.toLowerCase();
  const n = Number(version.split("-v")[1]);
  if (!texts[key] || n > texts[key].n) texts[key] = { n, version, title, intro, sections, closing };
}

mkdirSync(outDir, { recursive: true });
const consent = Object.fromEntries(Object.entries(texts).map(([k, v]) => [k, { version: v.version, title: v.title, intro: v.intro, sections: v.sections, closing: v.closing }]));
writeFileSync(
  join(outDir, "consent.ts"),
  `// GENERATED by scripts/sync-content.mjs from docs/consent-text/. Do not edit.\n` +
    `export const CONSENT_TEXT = ${JSON.stringify(consent, null, 2)} as const;\n`,
);

const legal = { terms: read(join(docs, "TERMS.md")), privacy: read(join(docs, "PRIVACY.md")) };
writeFileSync(
  join(outDir, "legal.ts"),
  `// GENERATED by scripts/sync-content.mjs from docs/. Do not edit.\n` +
    `export const LEGAL = ${JSON.stringify(legal, null, 2)} as const;\n`,
);
console.log(`consent texts: ${Object.values(texts).map((t) => t.version).join(", ")}; legal pages: 2`);
